version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wine_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wine_inventory
      - JWT_SECRET=docker-local-jwt-secret-key
      - EMAIL_USER=mock@example.com
      - EMAIL_PASS=mock-password
      - BASE_URL=http://localhost:5000
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: